# GitHub Pages Configuration
title: NullStore
description: Fast, clean catalog for the latest patched (ReVanced, Revanced Extended, MorpheApp, RVX Morphed, and Revanced Advanced) Android apps and modules
url: https://nullcpy.github.io/
repository: nullcpy/nullcpy.github.io

# Theme (optional)
theme: null

# Build settings
markdown: kramdown
exclude:
  - README.md
  - .gitignore
  - .nojekyll
